# Generated by Django 4.0.3 on 2022-03-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_profile_department_profile_email_profile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
